name: MineBlocks
description: Easy to use plugin, that allows you to create "Mine blocks" on your server
version: 1.2.2
main: cz.raixo.blocks.MineBlocksPlugin
author: RAIXOCZ
website: https://discord.gg/gTKvK48Par
api-version: 1.16
softdepend:
  - DecentHolograms
  - CMI
  - Essentials
  - UltraAFK
  - AFKPlus
commands:
  mineblocks:
    aliases:
      - mb
      - mineb
